export const NICE_CLASSES = [
  { value: "1", label: "Class 1 — Chemicals" },
  { value: "2", label: "Class 2 — Paints, varnishes, lacquers" },
  { value: "3", label: "Class 3 — Cosmetics, cleaning preparations" },
  { value: "4", label: "Class 4 — Industrial oils, fuels" },
  { value: "5", label: "Class 5 — Pharmaceuticals" },
  { value: "6", label: "Class 6 — Common metals" },
  { value: "7", label: "Class 7 — Machines, machine tools" },
  { value: "8", label: "Class 8 — Hand tools" },
  { value: "9", label: "Class 9 — Scientific, electrical apparatus" },
  { value: "10", label: "Class 10 — Medical apparatus" },
  { value: "11", label: "Class 11 — Lighting, heating, cooking" },
  { value: "12", label: "Class 12 — Vehicles" },
  { value: "13", label: "Class 13 — Firearms, explosives" },
  { value: "14", label: "Class 14 — Precious metals, jewellery" },
  { value: "15", label: "Class 15 — Musical instruments" },
  { value: "16", label: "Class 16 — Paper, printed matter" },
  { value: "17", label: "Class 17 — Rubber, plastics" },
  { value: "18", label: "Class 18 — Leather goods, luggage" },
  { value: "19", label: "Class 19 — Building materials" },
  { value: "20", label: "Class 20 — Furniture, mirrors" },
  { value: "21", label: "Class 21 — Household utensils" },
  { value: "22", label: "Class 22 — Ropes, tents, tarpaulins" },
  { value: "23", label: "Class 23 — Yarns, threads" },
  { value: "24", label: "Class 24 — Textiles, bed covers" },
  { value: "25", label: "Class 25 — Clothing, footwear" },
  { value: "26", label: "Class 26 — Lace, embroidery, buttons" },
  { value: "27", label: "Class 27 — Carpets, rugs, mats" },
  { value: "28", label: "Class 28 — Games, toys, sporting goods" },
  { value: "29", label: "Class 29 — Meat, fish, dairy products" },
  { value: "30", label: "Class 30 — Coffee, tea, pastry" },
  { value: "31", label: "Class 31 — Agricultural products, seeds" },
  { value: "32", label: "Class 32 — Beers, mineral waters" },
  { value: "33", label: "Class 33 — Alcoholic beverages" },
  { value: "34", label: "Class 34 — Tobacco products" },
  { value: "35", label: "Class 35 — Advertising, business management" },
  { value: "36", label: "Class 36 — Insurance, financial affairs" },
  { value: "37", label: "Class 37 — Building construction, repair" },
  { value: "38", label: "Class 38 — Telecommunications" },
  { value: "39", label: "Class 39 — Transport, packaging, storage" },
  { value: "40", label: "Class 40 — Material treatment" },
  { value: "41", label: "Class 41 — Education, entertainment" },
  { value: "42", label: "Class 42 — Scientific, technological services" },
  { value: "43", label: "Class 43 — Food & drink services" },
  { value: "44", label: "Class 44 — Medical, veterinary services" },
  { value: "45", label: "Class 45 — Legal, security services" },
];
